public_files:
  - ".profile"
  - ".bash_profile"
  - ".bashrc"
  - ".zprofile"
  - ".zshrc"
  - ".exrc"
  - ".screenrc"
# ssh
  - ".ssh/"
  - ".ssh/authorized_keys"
# config
  - ".config/"
  - ".config/vim/**"
  - ".config/tmux/**"
  - ".config/htop/**"
# env
  - ".config/env/"
  - ".config/env/*"
  - ".config/env/bash/**"
  - ".config/env/zsh/**"
  - ".config/env/rc/"
  - ".config/env/rc/sudo"
  - ".config/env/rc/docker"
  - ".config/env/rc/tmux"

