public_files:
  - ".profile"
  - ".bash_profile"
  - ".bashrc"
  - ".zprofile"
  - ".zshrc"
  - ".exrc"
  - ".screenrc"
  - ".ssh/authorized_keys"
  - ".config"
  - ".config/vim"
  - ".config/vim/vimrc"
  - ".config/vim/*.vim"