public_files:
  - ".profile"
  - ".bash_profile"
  - ".bashrc"
  - ".zprofile"
  - ".zshrc"
  - ".exrc"
  - ".screenrc"
  - ".ssh/authorized_keys"
  - "dot_config/"
  - "dot_config/vim/vimrc"
  - "dot_config/vim/*.vim"