public_files:
  - ".profile"
  - ".bash_profile"
  - ".bashrc"
  - ".zprofile"
  - ".zshrc"
  - ".exrc"
  - ".screenrc"
# ssh
  - ".ssh/"
  - ".ssh/authorized_keys"
# config
  - ".config/"
  - ".config/tmux/**"
  - ".config/htop/**"
## vim
  - ".config/vim/"
  - ".config/vim/*"
  - ".config/vim/autoload/"
  - ".config/vim/autoload/plug.vim"
  - ".config/vim/plugged/"
  - ".config/vim/plugged/lightline.vim/**"
  - ".config/vim/plugged/nord-vim/**"
  - ".config/vim/plugged/trailertrash.vim/**"
  - ".config/vim/plugged/vim-ocsyank/**"
# env
  - ".config/env/"
  - ".config/env/*"
  - ".config/env/bash/**"
  - ".config/env/zsh/**"
  - ".config/env/rc/"
  - ".config/env/rc/sudo"
  - ".config/env/rc/docker"
  - ".config/env/rc/tmux"

