public_files:
  - ".profile"
  - ".bash_profile"
  - ".bashrc"
  - ".zprofile"
  - ".zshrc"
  - ".exrc"
  - ".vimrc"
  - ".screenrc"
# ssh
  - ".ssh/"
  - ".ssh/authorized_keys"
# config
  - ".config/"
  - ".config/tmux/*"
  - ".config/tmux/themes/"
  - ".config/tmux/themes/nord2.conf"
  - ".config/htop/**"
  - ".config/vim/**"
# shell
  - ".config/shell/"
  - ".config/shell/*"
  - ".config/shell/bash/**"
  - ".config/shell/zsh/**"
  - ".config/shell/rc/"
  - ".config/shell/rc/docker"
# local/bin
  - ".local/bin/"
  - ".local/bin/tm"
